### ISSUE TITLE
API key issues

### ISSUE THREAD

**Issue by anlodrve** [PrimeAcademy/amethyst-syllabus#10]
API key is not working when using same code in a new 

Andrea

**What do you want to happen?**
Extra set of debugging eyes

**What is actually happening?**
Google Maps Javascript API warning: NoApiKeys

## Screenshots / Code Snippets

<img width="305" alt="Screenshot 2023-03-15 at 1 25 22 PM" src="https://user-images.githubusercontent.com/116206804/225407100-d7e96b74-402b-4349-90f6-03996d69cdfe.png">

## What did you try? Who did you ask?

Googled a lot 

## What branch is your code on? Did you git push?
I have made several solo project repos,  file name is flowerscouter, branch is map-first

## When was the last time you took a break?
Recently

**Comment by DoctorHowser** [comment]
IT WORKS....

Restart the client manually. IDK
