### ISSUE TITLE
Nested pool query error handling

### ISSUE THREAD

**Issue by johnmayou** [PrimeAcademy/amethyst-syllabus#11]
## Description

John Mayou

**What do you want to happen?**
To be able to handle errors on nested pool queries. 

**What is actually happening?**
When I set multiple res.send's inside each other, I get the too many headers being sent to the client error.

## Screenshots / Code Snippets

![Screenshot 2023-03-15 at 2 31 26 PM](https://user-images.githubusercontent.com/109235738/225422390-d0088e9b-e675-4c6d-bb83-ff1d74021ba9.png)

## What did you try? Who did you ask?
Haven't been able to figure this out for the past couple of weekend projects. Had conversations with people that couldn't figure it out either. Asked people in my pod, googling seems to be nesting multiple try-catch blocks inside each other, seems like there should be a better way.

**Comment by DoctorHowser** [comment]
transactions and async/await to the rescue
