### ISSUE TITLE
Look at LatLng

### ISSUE THREAD

**Issue by anlodrve** [PrimeAcademy/amethyst-syllabus#12]
## Description
trying to capture location data from a user click/touch event and there's an object in google maps javascript called LatLng but in react it behaves differently, and I would like you to look at it with me to see if you have any more insight 

**Your Name**
Andrea

**What do you want to happen?**

**What is actually happening?**
Cannot get lat or lng data 

## Screenshots / Code Snippets

window.google.maps.LatLng returns undefined 

## What did you try? Who did you ask?
lots and lots of googling and videos, and asked Anniessa 

## What branch is your code on? Did you git push?

flowerscouter (file) position-data (branch) 

## When was the last time you took a break?
about an hour ago

**Comment by DoctorHowser** [comment]
going to pivot away from the native js implementation

**Comment by DoctorHowser** [comment]
went to @react-google-map/api lib
