### ISSUE TITLE
Discussing Project Scope

### ISSUE THREAD

**Issue by sollambert** [PrimeAcademy/amethyst-syllabus#13]
## Description
Discussion of increasing project scope

**Your Name**
Solomon Lambert

**What do you want to happen?**
Discussion about project scope

**What is actually happening?**
I am not currently discussing project scope

## Screenshots / Code Snippets
![club-penguin-breakdance](https://user-images.githubusercontent.com/99863444/225647634-febeb22b-71ed-4cf3-96fd-8f5c873403a4.gif)

## What did you try? Who did you ask?
I am asking for a discussion of project scope right now on github.

## What branch is your code on? Did you git push?
main, everything is a-ok

## When was the last time you took a break?
Yesterday

**Comment by DoctorHowser** [comment]
Going to attempt an admin role and views
