### ISSUE TITLE
**NOT URGENT** nav bar question

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#17]
## Description

**Anniessa**

**What do you want to happen?**
labels to show up in my MUI bottom navigation bar 

**What is actually happening?**

no labels showing up

## Screenshots / Code Snippets

<img width="395" alt="Screenshot 2023-03-16 at 2 47 15 PM" src="https://user-images.githubusercontent.com/111613142/225736189-22004776-c4a6-4238-b8ab-a3c65673fb33.png">

## What did you try? Who did you ask?
I have showLabels in my <BottomNavigation> component but it's still not reading the labels I have set in <BottomNavigationAction>.
![Screenshot 2023-03-16 at 2 48 38 PM](https://user-images.githubusercontent.com/111613142/225736438-a71c4968-c951-4454-9369-7c588188937d.png)

## What branch is your code on? Did you git push?

bottom-nav

## When was the last time you took a break?
20 min ago

**Comment by DoctorHowser** [comment]
is is related to the rule of 3?

**Comment by anniessa** [comment]
No, it unfortunately didn't work :( It might have something to do with me
fixing the bottom nav position? But I was researching other apps (aka using
Twitter this morning) and there aren't any labels... but that's not best
practice for accessibility. I'll keep toolin' it to see if I can get
something. Might reupload images with labels already written.
