### ISSUE TITLE
Server not restarting on file change

### ISSUE THREAD

**Issue by cyrilmb** [PrimeAcademy/amethyst-syllabus#19]
## Description

**Your Name**

Cyril

**What do you want to happen?**
I want the server to restart when I save changes 
**What is actually happening?**

Nothing. I have to manually restart the server in order for changes that I made to take effect.

## What did you try? Who did you ask?
I checked for nodemon and tried installing it again. I asked Connor and John. They said you need some serious halp.

Client side changes automatically update, so I have no idea why server side doesn't.

I googled "nodemon not restarting server," and the results were either for old versions, recommended that I downgrade, or were not relevant.

## What branch is your code on? Did you git push?
on main now, but this problem happens on every branch 

## When was the last time you took a break?
maybe 30 mins ago?

**Comment by DoctorHowser** [comment]
used .jsx extension on the serverside
