### ISSUE TITLE
checkbox tags

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#2]
## Description

**Anniessa**

**What do you want to happen?**

**What is actually happening?**

tags are not being populated in redux state

## What did you try? Who did you ask?

I believe it has something to do with how I'm setting the value (or rather NOT setting the value) but I'm not sure if there is something special that needs to happen for checkboxes. 

Asked a couple of cohort mates, but checkboxes are tricksy!

## What branch is your code on? Did you git push?
tags-setup

## When was the last time you took a break?
just got back from lunch!

**Comment by DoctorHowser** [comment]
Got it!
