### ISSUE TITLE
journey into a PUT with a relational table

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#20]
## Description

**Anniessa**

**What do you want to happen?**
I need to be able to update a post and its related tags.

**What is actually happening?**

Just wanna chat through the process and work out some next steps/directions.

## What did you try? Who did you ask?
I've talked to a couple folks.

## What branch is your code on? Did you git push?
put-request

## When was the last time you took a break?
10 min ago!

**Comment by DoctorHowser** [comment]
Going to delete all tags and re-insert

**Comment by DoctorHowser** [comment]
I think you got it.
