### ISSUE TITLE
details from api & user

### ISSUE THREAD

**Issue by heidign** [PrimeAcademy/amethyst-syllabus#21]
## Description

**Your Name**
Heidi

**What do you want to happen?**
I want to to get api details and user-inputted info in my plant detail view

**What is actually happening?**

I am only able to get the info from the user

## What did you try? Who did you ask?
I've talking with John and Connor from pod.

I am preemptively asking because I know I don't fully understand how this works. My issue/confusion is not understanding how I can get all the details together from different reducers  and sagas.

I've been looking at redux/sagas docs.

## What branch is your code on? Did you git push?
I am starting a new branch now. I will call it details and commit.

## When was the last time you took a break?
just came back from making lunch and watering plants!

**Comment by DoctorHowser** [comment]
Heidi, I can meet after 3 this afternoon -- but the idea i think you need to think through is
`What data do I want in the DB, and where does it come from?` It sounds like you're able to collect the user generated data in the DB, so we need to figure out what data you want in the DB that comes from your API and where it's located.

**Comment by DoctorHowser** [comment]
GOnna use https://github.com/PrimeAcademy/amethyst-syllabus/blob/main/lecture-notes/week-14-solo-project/14-03_redux-edit.md
