### ISSUE TITLE
Conditional Insert, Checking Foreign Key in Relational Database

### ISSUE THREAD

**Issue by sollambert** [PrimeAcademy/amethyst-syllabus#22]
## Description

**Your Name**
Solomon

**What do you want to happen?**
I want to insert into a relational database, only if the user id matches the user_id column in another database that is not being inserted into.

**What is actually happening?**
Have no idea how to pull this off.

## Screenshots / Code Snippets

    INSERT INTO "rooms_items" ri (room_id, item_id)
//want something like this
//JOIN items i ON ri.item_id = i.id
//JOIN rooms r ON ri.room_id = r.id
//JOIN games g ON g.id = r.game_id
//WHERE g.user_id = $3
    VALUES($1, $2);

## What did you try? Who did you ask?

I tried googling and found nothing helpful.

## What branch is your code on? Did you git push?
main, not pushed, but not really an error, more not knowing how to do it.

## When was the last time you took a break?

Hour ago

**Comment by DoctorHowser** [comment]
Going to need some Authorization level stuff -- gotta check if the game_id is a users
