### ISSUE TITLE
SQL query

### ISSUE THREAD

**Issue by bencapp** [PrimeAcademy/amethyst-syllabus#23]
## Description

Ben Capp

**What do you want to happen?**
I'm trying to get a SQL query that will return data from 4 tables total.

**What is actually happening?**
The query that I am running returns multiple instances of elements in the JSON_AGG arrays.

## Screenshots / Code Snippets
This is the command that works as intended:

`SELECT story.title, story.speed_type, story.length_type, 
JSON_AGG(text.text) AS text_array, 
JSON_AGG(text.timestamp) AS timestamp_array
FROM story 
JOIN "text" ON story.id = text.story_id
WHERE story.public = true
GROUP BY story.id;`

Here is the output:
<img width="1292" alt="Screen Shot 2023-03-17 at 2 27 23 PM" src="https://user-images.githubusercontent.com/104331754/226001066-b61e553d-025b-4db6-b3ab-c2b2ba44da4d.png">

The text_array and text_timestamp columns are working as intended. 
However, now I want to get the users too:

`SELECT story.title, story.speed_type, story.length_type, 
JSON_AGG("user".username) AS contributor_array,
JSON_AGG("user".id) AS contributor_id_array,
JSON_AGG(text.text) AS text_array, 
JSON_AGG(text.timestamp) AS timestamp_array
FROM story 
JOIN user_story ON story.id = user_story.story_id
JOIN "user" on user_story.user_id = "user".id
JOIN "text" ON story.id = text.story_id
WHERE story.public = true
GROUP BY story.id;`

And now the output looks like this:

<img width="1463" alt="Screen Shot 2023-03-17 at 2 29 06 PM" src="https://user-images.githubusercontent.com/104331754/226001343-c39b5869-ba1d-4189-a345-da9bcefb5591.png">

All the fields are now put into the aggregated arrays twice.

## What did you try? Who did you ask?
All kinds of things! I looked online but it's hard to find an answer for this specific of an issue

**Comment by DoctorHowser** [comment]
json build object!
