### ISSUE TITLE
State out of sync / put request 

### ISSUE THREAD

**Issue by cjsimon250** [PrimeAcademy/amethyst-syllabus#24]
## Description

**Your Name**

CJ

**What do you want to happen?**

I am trying to construct a put request to update my menu_inventory table

**What is actually happening?**

My state is out of sync and not acting as desired

## Screenshots / Code Snippets

//UPDATE a menu item
router.put("/:id", rejectUnauthenticated, async (req, res) => {
  try {
    //Get id of the company belonging to the user
    const queryText = `SELECT * FROM company WHERE user_id = $1;`;
    const companyResult = await pool.query(queryText, [req.user.id]);
    const companyId = companyResult.rows[0].id;

    //New menu item data
    const updatedMenuItem = req.body.payload;
    const dish = updatedMenuItem.dish;
    const price = updatedMenuItem.price;
    const image = updatedMenuItem.image;
    //Array of new information
    const ingredients = updatedMenuItem.ingredients;

    const updateMenuQuery = `
  UPDATE menu SET "dish" = $1, price = $2, image = $3, company_id = $4 WHERE id = $5
  `;
    await pool.query(updateMenuQuery, [
      dish,
      price,
      image,
      companyId,
      req.params.id,
    ]);

    const clearMenuInventoryQuery = `
    DELETE FROM "menu_inventory" WHERE "menu_id" = $1
    `;
    await pool.query(clearMenuInventoryQuery, [req.params.id]);

    const updateMenuInventory = ingredients.map(async (ingredient) => {
      const updateMenuInventoryQuery = `
    INSERT INTO menu_inventory (menu_id, inventory_id, quantity, unit)
    VALUES ($1, $2, $3, $4);
    `;
      await pool.query(updateMenuInventoryQuery, [
        req.params.id,
        ingredient.id,
        ingredient.quantity,
        ingredient.unit,
      ]);
    });
    Promise.all(updateMenuInventory);
    res.sendStatus(200);
  } catch (error) {
    console.log("Error executing SQL query", ":", error);
    res.sendStatus(500);
  }
});

## What did you try? Who did you ask?

I tried multiple different ways to  structure my queries and given the first half of the query was working as intended I've narrowed it down to the second very hacky half

I googled how to compare old data with incoming data from a put request and couldn't find anything that was very helpful. I figured I should ask for help before trying to filter it myself again

## What branch is your code on? Did you git push?

menu-component

## When was the last time you took a break?

45 min ago

**Comment by DoctorHowser** [comment]
SQL needs to be sorted out, then figure out what else is wrong
