### ISSUE TITLE
unfortunately another journey into a put error

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#26]
## Description

**Anniessa**

**What do you want to happen?**
I want to be able to see the previously selected tag values when the editing view pops up. 
I think it has to do with being able to call the array of tags related to the clicked-on post and have it re-render (like how other fields are re-rendered with information).

**What is actually happening?**

## Screenshots / Code Snippets

<img width="328" alt="Screenshot 2023-03-17 at 5 59 33 PM" src="https://user-images.githubusercontent.com/111613142/226066729-7f6e22c9-b41c-4711-9350-680f52f6fde8.png">
This might be the root of the issue - on opening up the editing view, tags do not show up.
However, when I click on another path, the tags show up again (but not pre-populated like the other fields)
<img width="322" alt="Screenshot 2023-03-17 at 6 03 13 PM" src="https://user-images.githubusercontent.com/111613142/226066958-9fd26672-12b1-4330-b247-0d3c7d12367a.png">

<img width="769" alt="Screenshot 2023-03-17 at 6 07 26 PM" src="https://user-images.githubusercontent.com/111613142/226067251-c07543eb-356c-480c-8951-b17ad6126d43.png">
this is the error I'm getting. This error log is found here in my post.saga. 

<img width="719" alt="Screenshot 2023-03-17 at 6 08 07 PM" src="https://user-images.githubusercontent.com/111613142/226067279-e2f97819-07b1-4511-af79-3d1d8db8f102.png">

Seems like it doesn't like the action.payload is happy.
<img width="768" alt="Screenshot 2023-03-17 at 6 08 50 PM" src="https://user-images.githubusercontent.com/111613142/226067329-a3c6633f-5760-46ca-9b05-e364942459a3.png">

## What did you try? Who did you ask?
I tried making a new reducer to store my tag_post relationship data, but it is also console.logging empty.

Many folks have tried to troubleshoot.

## What branch is your code on? Did you git push?
put-request

## When was the last time you took a break?
gonna take a break now and come back to it but it feels like a major block

**Comment by DoctorHowser** [comment]
Think we solved this
