### ISSUE TITLE
Having to restart express server very often, server refuses requests after a short period of time

### ISSUE THREAD

**Issue by sollambert** [PrimeAcademy/amethyst-syllabus#27]
## Description

**Your Name**
Solomon Lambert

**What do you want to happen?**
My server to run without forcing me to restart it every minute and a half.

**What is actually happening?**
Express server fails silently, requests are still made from the client but are never acted upon by the server and never time out. I have tested this issue with multiple browsers and postman and the issue is definitely on the server end of the application. If it fails, ALL requests from ALL clients are refused.

## Screenshots / Code Snippets
There are no errors, or logs of anything failing. After a certain amount of requests to the express server its stops responding and the sent requests will never resolve or time out.

## What did you try? Who did you ask?
I spent roughly 3 hours googling the issue and looked into certain packages that deal with max socket connections and keeping socket connections open per user with subsequent requests. I attempted closing requests at the end of server-side routes with res.end() to prevent superfluous unused sockets. 

I also tried manually setting the keepAliveTimeout and headersTimeout variables for the express server, which didn't improve or fix the problem.

## What branch is your code on? Did you git push?
main

## When was the last time you took a break?
I just woke up, made tea, and started investigating the issue.

**Comment by sollambert** [comment]
I also tried updating passport middleware to 0.6.0, hoping that'd fix the issue if it was related to the authentication middleware.

**Comment by DoctorHowser** [comment]
Make sure you are always sending a response. Makes sure you close any connections for transactions

**Comment by sollambert** [comment]
I've double and triple checked every route in my server, they're all being closed and the SQL connections are also being closed.

**Comment by sollambert** [comment]
:face_exhaling: looks like I forgot the parenthesis on every single connection.release in my app. I'll fix that and see if it did anything :laughing:

**Comment by sollambert** [comment]
Yup, classic case of "maybe if I step away and look at it again, I'll find it"
