### ISSUE TITLE
Decoupling From API

### ISSUE THREAD

**Issue by heidign** [PrimeAcademy/amethyst-syllabus#30]
## Description

**Your Name**

Heidi

**What do you want to happen?**
I am looking to sort out API requests logistics between reducers and sagas to de-bug. 
somewhere I am firing too many requests and need help before I hit max again today.

**What is actually happening?**

`[nodemon] 2.0.21
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/server.js`
Listening on port: 5000
REQ.PARAMS.ID: 47
REQ.PARAMS.ID: 47
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
REQ.PARAMS.ID: 46
[nodemon] restarting due to changes...`

## What did you try? Who did you ask?
I am logging. I asked Solomon. Briefly chatted with pod members this morning.

## What branch is your code on? Did you git push?
details-view

## When was the last time you took a break?
going now.

**Comment by DoctorHowser** [comment]
May need to pay to get this to go away. limited to 300 a day
