### ISSUE TITLE
Database fail

### ISSUE THREAD

**Issue by Zabdi94** [PrimeAcademy/amethyst-syllabus#31]
## Description

**Your Name**
Zakariye Abdi

**What do you want to happen?**
I want to display my data to the database and show "watchlist" on the about page.

**What is actually happening?**
The watchlist button works, but nothing is rendering on the about page, It was working when I set movieApi.jsx line 40 to "SET_WATCHED" but I had to switch over to the POST which is ADD_MOVIE. I can't keep my watchlist to stay when I refresh mainly because of the database problem i'm having.

## What did you try? Who did you ask?
I got some tips from Nolan, and tried to console.log everything.

There wasn't much I googled, but I did reference my past projects.

## What branch is your code on? Did you git push?
Currently on main, and yes i did push

## When was the last time you took a break?
Lunch

**Comment by DoctorHowser** [comment]
needed to call the GET for watchlist. Next step is to do another round of GETs to the API by id.
