### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by Zabdi94** [PrimeAcademy/amethyst-syllabus#32]
## Description

**Your Name**
Zak abdi

**What do you want to happen?**
get rid or be able to render that specific picture in the api
**What is actually happening?**
That picture is causing everything to be undefined.

## Screenshots / Code Snippets

<img width="1434" alt="Screen Shot 2023-03-20 at 4 04 30 PM" src="https://user-images.githubusercontent.com/113937204/226465999-52dd573a-cde2-4677-8b96-0996e42c8636.png">

<img width="1438" alt="Screen Shot 2023-03-20 at 4 04 52 PM" src="https://user-images.githubusercontent.com/113937204/226466012-09f227ee-dcb5-49b7-bb86-37da8a338956.png">

<img width="1214" alt="Screen Shot 2023-03-20 at 4 07 45 PM" src="https://user-images.githubusercontent.com/113937204/226466140-b6c7f54e-28a9-402a-8805-06503dc639b8.png">

## What did you try? Who did you ask?
I tried to block the request from chrome

## What branch is your code on? Did you git push?
Main

## When was the last time you took a break?
at 2:30

**Comment by DoctorHowser** [comment]
You need to save the correct ID for the movie in your DB.
Once you do that, then you can make a GET movie/{movieId} request to the API
