### ISSUE TITLE
weird things happening in edit

### ISSUE THREAD

**Issue by anlodrve** [PrimeAcademy/amethyst-syllabus#33]
## Description

**Your Name**
Andrea

**What do you want to happen?**
Trying to get a marker at my original location to show up in edit mode, and then be able to click again and change the location of the marker 
**What is actually happening?**
a bunch of inconsistent errors. it's saying variables are undefined only sometimes, I think it has to be something to do with async stuff. 

cannot read properties of undefined 

## Screenshots / Code Snippets
![Screenshot 2023-03-20 at 4 11 23 PM](https://user-images.githubusercontent.com/116206804/226466888-b1d04668-1798-4fef-8c8a-887503b49518.png)

<img width="341" alt="Screenshot 2023-03-20 at 4 09 58 PM" src="https://user-images.githubusercontent.com/116206804/226466669-4e386e37-17a2-4b39-8cb1-cee37b05b83e.png">

## What did you try? Who did you ask?

Lots of trial and error

**Comment by DoctorHowser** [comment]
going to use a reducer and lecture notes
