### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#34]
## Description

**Anniessa**

**What do you want to happen?**
global language translation - I installed the google translate API and it is saying that there is a missing module in node, but my node_modules does have child_process.
**What is actually happening?**

<img width="389" alt="Screenshot 2023-03-20 at 8 21 51 PM" src="https://user-images.githubusercontent.com/111613142/226498377-e4eca05b-7f05-415a-a14d-ef377896f36c.png">
<img width="672" alt="Screenshot 2023-03-21 at 8 06 41 AM" src="https://user-images.githubusercontent.com/111613142/226615104-3b368f3e-9694-484f-981e-a9f8f11120f7.png">

## What did you try? Who did you ask?
I wanted to re-install the missing node module but I don't want to break it further.

When you have a chance, I would like to go over the different areas that this could live in the app - my instinct is the index.html, but a brief walkthrough would be appreciated! 

## What branch is your code on? Did you git push?
translation

## When was the last time you took a break?
had a good sleep!

**Comment by DoctorHowser** [comment]
Did you install anything new? When did this start happening? It looks like a strange error.
