### ISSUE TITLE
Stretch goals

### ISSUE THREAD

**Issue by heidign** [PrimeAcademy/amethyst-syllabus#38]
## Description

**Your Name**

Heidi

**What do you want to happen?**

Checkbox to indicate offer status or to change the structure of db, adding an offer table

**What is actually happening?**

I am not sure how to store a default value of boolean-type data in redux state for edit reducer. I am getting errors that's indicating the isOffered is 'ON' but cannot get it to update in db.

## What did you try? Who did you ask?
Pod-mates, stack exchanges, YouTube, google

## What branch is your code on? Did you git push?
main

**Comment by DoctorHowser** [comment]
Making progress! Gotta get the put solidified, but youre almost there

**Comment by DoctorHowser** [comment]
solved with help from peers
