### ISSUE TITLE
SQL question

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#4]
## Description

**Anniessa**

**What do you want to happen?**
I want to store an array in one table column.

**What is actually happening?**

In my router, I put ARRAY around the value I want to be an array. When I tried to reset my table so that value is also an array, I am getting the following errors.

## Screenshots / Code Snippets

**SERVER TERMINAL:**
Error posting post with tag error: column "tags_id" is of type integer but expression is of type text[]
![Screenshot 2023-03-14 at 5 17 14 PM](https://user-images.githubusercontent.com/111613142/225154769-7b75ca41-7343-44d0-97c0-67a910e86a43.png)

**In PostgreSQL:**
<img width="486" alt="Screenshot 2023-03-14 at 5 16 23 PM" src="https://user-images.githubusercontent.com/111613142/225154651-68279476-e344-4d04-9ee5-c285dd4b8cb8.png">

<img width="1037" alt="Screenshot 2023-03-14 at 5 16 51 PM" src="https://user-images.githubusercontent.com/111613142/225154705-c9dbd851-e599-4ccb-8811-e4643b0a8123.png">

## What did you try? Who did you ask?

I researched ALTER table and tried that (https://tableplus.com/blog/2018/08/postgresql-how-to-add-a-foreign-key.html), but I'm still not able to make the table I need in order to alter it.

## What branch is your code on? Did you git push?
sql-issue

## When was the last time you took a break?
Going to take a break now!! Hope we can connect in the morning. THANK YOU!!!!

**Comment by DoctorHowser** [comment]
Hint- it’s a many to many relationship. You need a table to manage the post tags

**Comment by DoctorHowser** [comment]
Need to insert a row for each tag, not an array.

**Comment by anniessa** [comment]
GOT IT! happy to show you when you have a moment :~)
