### ISSUE TITLE
Comments are not Commenting

### ISSUE THREAD

**Issue by anlodrve** [PrimeAcademy/amethyst-syllabus#40]
## Description

**Your Name**
Andrea

**What do you want to happen?**
Get request to get comments stored in database and render on page

**What is actually happening?**

500 Error - can't get. 
I'm trying to send a postId as a param to get the comments associated with the specific post. The postId is solid in my component, but as soon as I dispatch it to saga it becomes undefined. I think it's because I'm accidentally calling useEffect twice, once in a parent and once in a child component. The issue is I get the postId by mapping through an array of posts, and so I can't dispatch to get comments without it, so it feels like I need to send it as a prop to my child component, but then I'm useEffecting twice...HALP 

## Screenshots / Code Snippets
postId is normal here; 
![Screenshot 2023-03-22 at 11 29 59 PM](https://user-images.githubusercontent.com/116206804/227103458-9bf71bb2-281c-427c-9abf-70f7228ceb00.png)
Becomes undefined here: 
![Screenshot 2023-03-22 at 11 30 25 PM](https://user-images.githubusercontent.com/116206804/227103518-fbb662eb-ab38-4846-ba6e-65de63f0833f.png)

## What did you try? Who did you ask?

Asked Nolen, Anniessa, and CJ. we are all stumped! 

## What branch is your code on? Did you git push?

on branch comment. have not pushed. 
## When was the last time you took a break?
taken several tonight, it's still there

**Comment by DoctorHowser** [comment]
Went around the problem by doing a JSON_AGG of comments on posts

**Comment by DoctorHowser** [comment]
Used SQL JSON_AGG
