### ISSUE TITLE
Updating inventory query

### ISSUE THREAD

**Issue by cjsimon250** [PrimeAcademy/amethyst-syllabus#41]
## Description

**Your Name**

Cj

**What do you want to happen?**

When I submit a form the number of each menu item sold I need to subtract the right amount of each inventory item from the data base 

**What is actually happening?**

the ingredient is being subtracted but only from the first dish on the menu and it is being subtracted four times

## Screenshots / Code Snippets

//POST to new sales data
router.post("/", rejectUnauthenticated, async (req, res) => {
  //Get id of the company belonging to the user
  const companyQuery = `SELECT * FROM company WHERE user_id = $1;`;
  const result = await pool.query(companyQuery, [req.user.id]);

  let companyId = result.rows[0].id;
  const sales = req.body;
  //Mapping through the dish object
  const dishesList = Object.keys(sales.dishes);

  console.log("DISHES LIST :", dishesList);
  await Promise.all(
    dishesList.map(async (dish) => {
      const quantitySold = sales.dishes[dish].quantitySold;
      const menuId = sales.dishes[dish].quantitySold;

      //Inserting the total sales of the menu item into the database
      insertSalesQuery = `
      INSERT INTO "sales" (menu_id, date, "amountSold", company_id)
      VALUES($1, $2, $3, $4);
      `;

      await pool.query(insertSalesQuery, [
        menuId,
        sales.date,
        quantitySold,
        companyId,
      ]);

      //Getting the ingredients inside of the dish
      const selectIngredientQuery = `
      SELECT "menu_inventory".inventory_id, "menu_inventory".quantity FROM "menu_inventory"
      WHERE "menu_inventory".menu_id = $1;
      `;

      //Getting the id's of inventory items to subtract quantity from
      const menuIventoryResult = await pool.query(selectIngredientQuery, [
        menuId,
      ]);
      const inventoryData = menuIventoryResult.rows;

      console.log("INEVENTORY DATA : ", inventoryData);
      await Promise.all(
        inventoryData.map(async (inventoryObject) => {
          let inventoryId = inventoryObject.inventory_id;
          let quantityInDish = inventoryObject.quantity;

          // console.log("Inventory ID", inventoryId);
          // console.log("Quantity in Dish", quantityInDish);

          //Getting the current quantity if this item in the inventory
          const inventoryQuery = `
          SELECT "inventory".quantity FROM "inventory"
          WHERE id = $1;`;

          const inventoryResult = await pool.query(inventoryQuery, [
            inventoryId,
          ]);
          let quantityInStock = inventoryResult.rows[0].quantity;
          // console.log("Quantity in Stock", quantityInStock);

          //Determining the amount of a specific inventory item consumed
          let amountConsumed = quantityInDish * quantitySold;

          // console.log("Amount Consumed", amountConsumed);

          //Determing current stock of item after today's sales
          let newInventoryAmount = quantityInStock - amountConsumed;

          // console.log("NEW TOTAL :", newInventoryAmount);
          const updateInventoryQuery = `
        UPDATE "inventory" SET "quantity" = $1 WHERE id = $2
        `;

          await pool.query(updateInventoryQuery, [
            newInventoryAmount,
            inventoryId,
          ]);
        })
      );
    })
  );
});

## What did you try? Who did you ask?

I have tried to console log all of my variables every step of the way and restructure my maps but I can't seem to get it to work

## What branch is your code on? Did you git push?

sales-dashboard

## When was the last time you took a break?

45 mins ago

**Comment by vkarlen** [comment]
After some digging, `menuId` was not being correctly captured in the sales POST as the value is being set as `sales.dishes[dish].quantitySold`. In testing, setting all the quantities sold as 1 then makes it look as if it only subtracts off the first menu item. Very tricky error!

**Comment by cjsimon250** [comment]
Query is being fed all of the correct data to subtract but is updating the wrong amount in the database

          console.log(
            "INVENTORY ID:",
            inventoryId,
            "AMOUNT CONSUMED :",
            amountConsumed,
            "QUANTITY IN STOCK BEFORE CHANGE :",
            quantityInStock,
            "NEW AMOUNT : ",
            newInventoryAmount
          );
With the above code and this console log I am given 
INVENTORY ID: 1 AMOUNT CONSUMED : 8 QUANTITY IN STOCK BEFORE CHANGE : 214 NEW AMOUNT :  206
for each inventory item but when the amount is updated in the database inventory item with id of 1 will be set to 204 instead of 206
