### ISSUE TITLE
some functionality not working for other users

### ISSUE THREAD

**Issue by anniessa** [PrimeAcademy/amethyst-syllabus#44]
## Description

**Anniessa**

**Different users to be able to edit their posts**

**No edit or delete buttons showing up on new user post**

## What branch is your code on? Did you git push?
multer

## When was the last time you took a break?
5 min ago

**Comment by vkarlen** [comment]
Buttons were being covered due to the size of the Card's contents. Moving them to a `<Card Action>` outside of the content allowed them to show
