### ISSUE TITLE
Edit menu dialog box glitching out

### ISSUE THREAD

**Issue by cjsimon250** [PrimeAcademy/amethyst-syllabus#45]
## Description

**Your Name**

CJ

**What do you want to happen?**

the form to render with all the data

**What is actually happening?**

the form renders and has the necessary data but it is glitching out. The data is clearing or it is going all black or sections of it are changing on hover

no error messages

## Screenshots / Code Snippets

<img width="524" alt="Screen Shot 2023-03-23 at 1 29 24 PM" src="https://user-images.githubusercontent.com/116697704/227312930-ce2c38cb-54bb-4084-ab3c-220c0124f484.png">

## What did you try? Who did you ask?

I asked John but we both cannot figure out wha the problem might be

I googled looking for rendering problems with mui dialog boxes but could not find anything and I am using them in multiple places where they are working perfectly

## What branch is your code on? Did you git push?

sales-dashboard

## When was the last time you took a break?
20 min ago

**Comment by DoctorHowser** [comment]
♾️ modals opening.
