### ISSUE TITLE
Authorization Postman OAuth 2.0

### ISSUE THREAD

**Issue by johnmayou** [PrimeAcademy/amethyst-syllabus#53]
We are trying to authenticate our postman with story forge's OAuth authentication. We imported the openapi.json into postman and it populated the code and token url. For client ID, client secret, scope and state for us. Would these params be things that we get from our clients themselves? Not sure to ask or not?

![Screenshot 2023-04-04 at 2 09 52 PM](https://user-images.githubusercontent.com/109235738/229895649-1d9662ff-0467-4a78-874b-c7accb3969c0.png)

**Comment by DoctorHowser** [comment]
Yes, those would be things to ask the client about. Your app likely would need an id and a secret, scope is likely read, but need to confirm, unsure about state.
