### ISSUE TITLE
Uncaught reference error with Babel when attempting to implement video.js

### ISSUE THREAD

**Issue by sollambert** [PrimeAcademy/amethyst-syllabus#54]
## Description

**Your Name**
Solomon Lambert

**What do you want to happen?**
VideoJS to load and display my video stream without exploding.

**What is actually happening?**
VideoJS cannot initialize properly as it seems some kind of import is undefined, despite existing within the node_modules folder on the correct version.

## Screenshots / Code Snippets
![Screen Shot 2023-04-10 at 9 16 41 AM](https://user-images.githubusercontent.com/99863444/230921706-8a750188-fbf7-4f4f-9431-cbd90c5f846f.png)

## What did you try? Who did you ask?
Initially, I attempted tracing down where the reference error exists within the babel source, to ensure it did indeed exist within my node_modules folder. After confirming its existence, I looked through both my package.json and my package-lock.json to confirm the dependencies were the same for all of the packages required by video.js between my test project where video.js is working and the Omi live repo. I can't see any issues here and it's driving me wild.

## What branch is your code on? Did you git push?
stream-server-integration.  Yes, I did push.

## When was the last time you took a break?
It's Monday at 9:30AM and I had a nice relaxing weekend.

**Comment by DoctorHowser** [comment]
There was a transpiling issue from the library. https://github.com/videojs/video.js/issues/8170

// eslint-disable-next-line import/no-webpack-loader-syntax
import videojs from "!video.js";
