### ISSUE TITLE
Auth Discussion

### ISSUE THREAD

**Issue by sollambert** [PrimeAcademy/amethyst-syllabus#55]
## Description

**Your Name**
Solomon Lambert

**What do you want to happen?**
My stream authentication to be up to standards.

**What is actually happening?**
It has not been verified to be up to standards

## Screenshots / Code Snippets
N/A

## What did you try? Who did you ask?
I made auth but need Dane to look at it to confirm it's secure.

## What branch is your code on? Did you git push?
Merged to main

## When was the last time you took a break?
N/A

**Comment by emkerber** [comment]
Looked over NodeMediaServer auth code together, streams seem secure so far!
