### ISSUE TITLE
req.body

### ISSUE THREAD

**Issue by bencapp** [PrimeAcademy/amethyst-syllabus#58]
## Description

Ben Capp

**What do you want to happen?**
I want my GET endpoint to receive a req.body from my front end

**What is actually happening?**

The endpoint receives an empty body. The endpoint works fine when testing with postman, and the data that I am sending is in the correct form in the saga on the client side. All the code is accurate, as far as Andrea and I can see

## Screenshots / Code Snippets

SAGA: 

function* fetchProductInStream(action) {
  try {
    console.log("fetching product in stream, action.payload:", action.payload);
    const response = yield axios.get("/api/streams-products", {
      payload: action.payload,
    });
    yield put({ type: "SET_PRODUCT_IN_STREAM", payload: response.data });
  } catch (error) {
    console.log("Error with fetchProductInStream saga:", error);
  }
}

## What did you try? Who did you ask?
I've tried changing the data structure, testing with postman, testing other routes. Andrea and I looked at it together

## What branch is your code on? Did you git push?
streams-products, just pushed

## When was the last time you took a break?
going to lunch now

**Comment by DoctorHowser** [comment]
NO BODY ON GET
