### ISSUE TITLE
SQL joins

### ISSUE THREAD

**Issue by bencapp** [PrimeAcademy/amethyst-syllabus#6]
## Description

Ben Capp

**What do you want to happen?**
I'm trying to do a SQL join so that I can get information from two separate users in the user table and include them in the response. Currently my SQL query looks like this:

`SELECT invite.id, invite.sender_user_id, invite.recipient_user_id, invite.story_id, 
                    "user".username AS sender_user_username FROM invite 
                    JOIN "user" on "user".id = invite.sender_user_id
                    WHERE recipient_user_id = $1;`

And output looks something like this:

{
    id: 69,
    sender_user_id: 3,
    recipient_user_id: 4,
    story_id: 67,
    sender_user_username: 'connor'
  }

I just want to include a recipient_user_username as well, but I'm not sure how to structure the SQL query so that it can join onto the same table twice at different IDs.

**What is actually happening?**

## What did you try? Who did you ask?
I looked online but nothing is very helpful for this specific situation.

## What branch is your code on? Did you git push?
not really relevant

## When was the last time you took a break?
Just started this morning!!

**Comment by DoctorHowser** [comment]
aliasing tables to the rescue!
