### ISSUE TITLE
Authentication middleware with SQL queries

### ISSUE THREAD

**Issue by johnmayou** [PrimeAcademy/amethyst-syllabus#60]
## Description

John Mayou

We are trying to protect our endpoints from unauthorized users. Things like "Is the user the owner of this circle?" if "Yes" then they can remove members, if not then return 403. I'm wondering if having SQL queries inside of middleware is a bad practice or if there is a better way. We have to protect multiple endpoints with the same logic and I'm trying to keep the code base DRY.

This is an example of what my isCircleOwner middleware would look like. Thanks!

![Screenshot 2023-04-14 at 9 52 53 AM](https://user-images.githubusercontent.com/109235738/232078742-f8e7ca98-8497-4321-bb0e-f07e900b5222.png)

**Comment by DoctorHowser** [comment]
Updating the req.user to include ids of the circles they are admins of.
