### ISSUE TITLE
Asynchronous architecture of stripe checkout session

### ISSUE THREAD

**Issue by johnmayou** [PrimeAcademy/amethyst-syllabus#7]
## Description

John Mayou

**What do you want to happen?**
### Problem 1
Figuring out how to architect the stripe checkout session to only allow the user to join a cohort when they have paid. 
- Way 1: Send the user data in metadata to Stripe, then when I get a webhook for that checkout event success, I can add it to the database.
- Way 2: Send the user data to the database immediately, then when I get a webhook from Stripe for the event, I can toggle a `isActive` flag to `true`

**Comment by DoctorHowser** [comment]
go with way 1.
