### ISSUE TITLE
issues with search endpoint 

### ISSUE THREAD

**Issue by heidign** [PrimeAcademy/amethyst-syllabus#8]
## Description

**Your Name**
Heidi 

**What do you want to happen?**
I want to use the search endpoint to search by case-insensitive plant name and receive possible matches by exact, latin name, common name, etc.

**What is actually happening?**
I am receiving all 6000 plants. My search input is making a request with every keystroke.

## Screenshots / Code Snippets

![Screen Shot 2023-03-15 at 10 29 27 AM](https://user-images.githubusercontent.com/98715838/225359512-22010aa6-8e3b-4d88-b6d4-4423747b4273.png)

## What did you try? Who did you ask?

- I have looked at the **search router** -- trying different paths.
- I have looked at the **search reducer** -- added `SET_FOUND`
- I have looked at the **search saga** -- looking at the payload `apiResponse.data`,  used select to select search reducer to declare params and use it in the axios.get as `{params}` of my api/search
- I created a new **Search** component to start over, dispatching` {q: newSearch}`

## What branch is your code on? Did you git push?
server, no

everything is broken
## When was the last time you took a break?
I haven't this morning yet

Ok thanks, going now

**Comment by DoctorHowser** [comment]
fixed up code to use query string, req.query.

Debugging steps:
Console log -- do not assume things are right.
