### ISSUE TITLE
DataBase Structure

### ISSUE THREAD

**Issue by nolenlawton** [PrimeAcademy/amethyst-syllabus#9]
## Description

Nolen Lawton

**What do you want to happen?**

I want to use various 'score values' based on the game that is being played

**What is actually happening?**

I would currently need to add a bunch of columns for every game but only use some depending on the game

## Screenshots / Code Snippets

<img width="329" alt="Screen Shot 2023-03-15 at 11 41 33 AM" src="https://user-images.githubusercontent.com/112827639/225379765-b8756406-d6a4-406e-9b70-be2e8ccf22da.png">

Does that image work^?

## What did you try? Who did you ask?

I talked to john and he had a similar solution to me , basically adding a bunch of columns in the score table... 

My problem with this is some of the games will not be dealing with those values.

## What branch is your code on? Did you git push?

Not code, but a question about DB structure

## When was the last time you took a break?

I just took a break and this problem isn't really holding me back. I am just wondering if there is a better way to solve this.

**Comment by DoctorHowser** [comment]
Add a Column of unit_of_measure
